name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REPOSITORY: helloworldrepository

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credetintials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env: 
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "${{ secrets.AWS_REGION }}"
          echo "${{ secrets.AWS_ECR }}"
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w5q2z5v3          
          docker build -t $AWS_REPOSITORY:$IMAGE_TAG .
          docker tag $AWS_REPOSITORY:$IMAGE_TAG ${{ secrets.AWS_ECR }}/$AWS_REPOSITORY:$IMAGE_TAG
          docker push ${{ secrets.AWS_ECR }}/$AWS_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::${{ secrets.AWS_ECR }}/$AWS_REPOSITORY:$IMAGE_TAG"
      
      - name: Download Task Definiton
        run: |
          aws ecs describe-task-definition --task-definition helloworldtask \
          --query taskDefinition > task-definition.json

      - name: Read Task Definiton
        run: cat task-definition.json

      - name: Update task-definition.json
        run: echo "`jq '.containerDefinitions[0].image = "${{ steps.build-image.outputs.image }}"' task-definition.json`" > task-definition.json

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: helloworldservice
          cluster: helloworldcluster

      - name: Force redeploy
        run: |
          aws ecs update-service --cluster helloworldcluster --service helloworldservice --force-new-deployment